@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
!define foreign_key(x) <i><u>x</u></i>
hide methods
hide stereotypes

table(member) {
	primary_key(member_id: BIGINT)
	name: VARCHAR_255
	school: VARCHAR_32
	email: VARCHAR_255
	phone: VARCHAR_12
	balance: FLOAT_6
	last_membership_payment: TIMESTAMP
	is_deleted: BIT_1
}

table(party) {
	primary_key(party_id: BIGINT)
	name: VARCHAR_255
	date: DATE
	normal_beer_price: FLOAT_6
	special_beer_price: FLOAT_6
	is_deleted: BIT_1
}

table(transaction) {
	primary_key(transaction_id: BIGINT)
	foreign_key(member_id: BIGINT)
	foreign_key(party_id: BIGINT)
	amount: FLOAT_6
	label: VARCHAR_255
	timestamp: TIMESTAMP
}

member <- transaction
transaction -> party

table(product) {
	primary_key(product_id: BIGINT)
	name: VARCHAR_255
	price: FLOAT_6
	type: VARCHAR_255
}

table(served_beers_party) {
	foreign_key(party_id: BIGINT)
	foreign_key(product_id: BIGINT)
	category: VARCHAR_8
}

product <- served_beers_party
party <-- served_beers_party

table(parameters) {
	primary_key(parameters: BIGINT)
	balance_too_low_threshold: FLOAT_6
	membership_cost: FLOAT_6
	membership_expiring_date: DATE
}

table(authentication_token) {
	primary_key(token_id: BIGINT)
	token_name: VARCHAR_4
	hashed_token: VARCHAR_255
}

@enduml