@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam nodesep 110
skinparam ranksep 10

package Model {
	class Party {
		- id: int
		- name: String
		- date: Date
		- numberOfAttendees: int
		- balance: float
		+ Party(id: int, name: String, date: Date, numberOfAttendees: int, balance: float)
	}
}

package Controller {
	interface RESTDataManager {
		+ getObject(ressource : String) : Map<String, Object>
		+ getArray(ressource : String) : List<Object>
		+ post(resource : String, jsonObject : Map<String, Object>)
		+ put(resource : String, jsonObject : Map<String, Object)
		+ delete(resource : String) : Map<String, Object>
	}

	class RESTfulDataManager {
		- host : String
		- port : String
		- authToken : String
		+ RESTfulDataManager(host : String, port : String, authToken : String)
	}

	RESTDataManager <.. RESTfulDataManager
		

	class PartyController{
		+ PartyController(dataManager : RESTDataManager)
		+ getAllParties() : List<Party>
	}

	RESTDataManager "- dataManager" <- PartyController
}

Party <. PartyController : Uses

@enduml
